version: 3

services:
  nginx:
    image: nginx:latest
    ports:
    - 8080:80
    volumes:
    - /home/vue/html:/usr/share/nginx/html
    - /home/vue/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
